openapi: 3.0.3
info:
  title: STD24038
  description: This is a specification of STD24038
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /health:
    get:
      responses:
        200:
          description: return Ok
          content:
            text/plain:
              schema:
                type: string
                example: Ok

  /phones:
    post:
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/phones'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/phones'


  /phones/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      responses:
        200:
          description: return phone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phones'
        404:
          description: phone Not found
          content:
            application/json:
              schema:
                type: string
                example: NOT FOUND


  /phones/{id}/characteristics:
    put:
      responses:
        200:
          description: put
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/characteristics'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/characteristics'




components:
  schemas:
    phones:
      properties:
        identifier:
          type: string
          format: uui
          example: S239
        brand:
          type: string
          example: flsdf
        model:
          type: string
          example: abcd
        characteristics:
          $ref: '#/components/schemas/characteristics'
    characteristics:
      properties:
        ram_memory:
          type: number
          example: 12
        rom_memory:
          type: number
          example: 64

  parameters:
    id:
      name: id
      in: path
      required: true
      example: 1


  
