openapi: 3.0.3
info:
  title: STD24038
  description: This is a specification of STD24038
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /health:
    get:
      responses:
        200:
          description: return Ok
          content:
            text/plain:
              schema:
                type: string
                example: Ok

  /phones:
    post:
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/phones'


  /phones/{id}:

  /phones/{id}/characteristics:

components:
  schemas:
    phones:
      properties:
        identifier:
          type: string
          format: uui
          example: S239
        brand:
          type: string
          example: flsdf
        model:
          type: string
          example: abcd
        characteristics:
          properties:
            ram_memory:
              type: number
              example: 12
            rom_memory:
              type: number
              example: 64


  
